new update for UCSC Transient Team web pages at footer
scimma/blast pull request #102
Opened 2022-08-05 00:55 UTC by SamLaiiii

Fixes #  .

## Description of the Change

## Checklist

Please check all that apply to your proposed changes

- [ ] HTML code change
- [ ] Added package dependency
- [ ] Added data
- [ ] Changed django model
- [ ] Documentation change
- [ ] Added or changed TaskRunner

### **Additional context**

2022-08-05 00:55 UTC, SamLaiiii commented
I think I push the wrong file, let me do it with the right one

2022-08-05 17:30 UTC, astrophpeter requested changes
Looks good overall, just some minor changes please :)

2022-08-05 17:30 UTC, astrophpeter commented on app/host/templates/host/base.html
> +                <span style="margin-left:2px"><span class="text">| UCSC Transitent team web pages
Looks good! Can you please change the class here to text-muted from text

2022-08-05 17:30 UTC, astrophpeter commented on app/host/templates/host/base.html
>          </footer>
Can you please put </div> on this line, you deleted it :)

2022-08-06 04:52 UTC, astrophpeter approved these changes
Looks great!

2022-08-06 04:53 UTC, merged